# Generated by Django 4.2.7 on 2023-11-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=60)),
                ('phone_nambern', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('reg_data', models.DateField()),
            ],
        ),
    ]
